# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 14:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('line1', models.TextField()),
                ('line2', models.TextField(blank=True, null=True)),
                ('postcode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('total_value', models.IntegerField()),
                ('date_started', models.DateField()),
                ('date_ended', models.DateField()),
                ('status', models.CharField(blank=True, choices=[('0', 'Draft'), ('1', 'Waiting'), ('2', 'Validated')], max_length=1)),
                ('medias', models.ImageField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('medias', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('siren', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('date_deleted', models.DateField()),
                ('medias', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('addresses', models.ManyToManyField(blank=True, to='web.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('medias', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Bundle')),
            ],
        ),
        migrations.CreateModel(
            name='PrizePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Prize')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_birthday', models.DateField(blank=True, null=True)),
                ('medias', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('addresses', models.ManyToManyField(blank=True, to='web.Address')),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('class_name', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField()),
                ('is_shareable', models.BooleanField()),
                ('is_followable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetworkEnterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Enterprise')),
                ('social_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.SocialNetwork')),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetworkProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Profile')),
                ('social_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.SocialNetwork')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='social_networks',
            field=models.ManyToManyField(blank=True, through='web.SocialNetworkProfile', to='web.SocialNetwork'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='social_networks',
            field=models.ManyToManyField(blank=True, through='web.SocialNetworkEnterprise', to='web.SocialNetwork'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bundle',
            name='categories',
            field=models.ManyToManyField(blank=True, to='web.Category'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Enterprise'),
        ),
    ]
