# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialNetworkEnterprise',
            new_name='SocialNetwork_Enterprise',
        ),
        migrations.RenameModel(
            old_name='SocialNetworkProfile',
            new_name='SocialNetwork_Profile',
        ),
    ]
