# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20161101_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='date_deleted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
