# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20161101_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialnetwork_enterprise',
            old_name='social_network',
            new_name='socialnetwork',
        ),
        migrations.RenameField(
            model_name='socialnetwork_profile',
            old_name='social_network',
            new_name='socialnetwork',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='social_networks',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_networks',
        ),
    ]
