# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20161101_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetworkLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('socialnetwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.SocialNetwork')),
            ],
        ),
        migrations.RemoveField(
            model_name='socialnetwork_enterprise',
            name='enterprise',
        ),
        migrations.RemoveField(
            model_name='socialnetwork_enterprise',
            name='socialnetwork',
        ),
        migrations.RemoveField(
            model_name='socialnetwork_profile',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='socialnetwork_profile',
            name='socialnetwork',
        ),
        migrations.DeleteModel(
            name='SocialNetwork_Enterprise',
        ),
        migrations.DeleteModel(
            name='SocialNetwork_Profile',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='socialnewtorks',
            field=models.ManyToManyField(blank=True, to='web.SocialNetworkLink'),
        ),
        migrations.AddField(
            model_name='profile',
            name='socialnewtorks',
            field=models.ManyToManyField(blank=True, to='web.SocialNetworkLink'),
        ),
    ]
