# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20161101_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterprise',
            old_name='socialnewtorks',
            new_name='social_networks',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='socialnewtorks',
            new_name='social_networks',
        ),
        migrations.RenameField(
            model_name='socialnetworklink',
            old_name='socialnetwork',
            new_name='social_network',
        ),
    ]
