# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20161101_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prizeposition',
            name='prize',
        ),
        migrations.AddField(
            model_name='prize',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='PrizePosition',
        ),
    ]
