# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20161101_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
