# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_prize_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='users',
        ),
        migrations.AddField(
            model_name='profile',
            name='enterprise',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Enterprise'),
        ),
    ]
