# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 18:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0010_auto_20161205_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highscore', models.IntegerField(default=0)),
                ('clicks', models.BigIntegerField(default=0)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Bundle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
