# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_bundle_total_clickers'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='last_clicks',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='score',
            name='regeneration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
