# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20161212_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='last_clicks',
            new_name='remaining_clicks',
        ),
    ]
