# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20170131_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bundle',
            old_name='medias',
            new_name='media',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='medias',
            new_name='media',
        ),
        migrations.RenameField(
            model_name='enterprise',
            old_name='medias',
            new_name='media',
        ),
        migrations.RenameField(
            model_name='prize',
            old_name='medias',
            new_name='media',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='medias',
            new_name='media',
        ),
    ]
