# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_score_last_clicks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='highscore',
        ),
    ]
