# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_remove_score_highscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='highscore',
            field=models.IntegerField(default=0),
        ),
    ]
